### ISSUE TITLE
启智+ gradio 启动的服务，前端出现error，后台报错 AttributeError: 'NoneType' object has no attribute 'temperature'

### ISSUE THREAD

**Issue by salile** [thomas-yanxin/LangChain-ChatGLM-Webui#102]
hello~ 启智+ gradio 启动的服务
前端：
![image](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/61910901/ca553de9-73a2-4617-8ea5-f5c3ea449050)

后台：
完整traceback：
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 289, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 990, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 832, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "app.py", line 215, in predict
    resp = knowladge_based_chat_llm.get_knowledge_based_answer(
  File "app.py", line 102, in get_knowledge_based_answer
    self.llm.temperature = temperature
AttributeError: 'NoneType' object has no attribute 'temperature'

**Comment by Lilacs** [comment]
遇到同样的问题
<img width="1578" alt="CleanShot 2023-07-23 at 04 10 47@2x" src="https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/4457402/b5a5b7dd-ad05-496e-ac9c-ecc89a2732e4">
<img width="1592" alt="CleanShot 2023-07-23 at 04 11 12@2x" src="https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/assets/4457402/e5340c43-45a0-45da-8cc6-9f55aaf60e02">

**Comment by Cordy27** [comment]
同样的问题有人解决了吗

**Comment by thomas-yanxin** [comment]
最近我修复一下
