### ISSUE TITLE
本地运行报错

### ISSUE THREAD

**Issue by Rivien2010** [thomas-yanxin/LangChain-ChatGLM-Webui#11]
Traceback (most recent call last):
  File "/Users/terry/Downloads/test/lib/python3.8/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/terry/Downloads/test/lib/python3.8/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/Users/terry/Downloads/test/lib/python3.8/site-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/terry/Downloads/test/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/terry/Downloads/test/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/terry/Downloads/test/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "app.py", line 143, in predict
    print(file_obj.name)
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by thomas-yanxin** [comment]
知识库文件传进去了么？或者是完全传进去了么？

**Comment by Rivien2010** [comment]
embedding_model_dict = {
    "ernie-tiny": "nghuyong/ernie-3.0-nano-zh",
    "ernie-base": "./data/ernie-3.0-base-zh",
    "ernie-medium": "nghuyong/ernie-3.0-medium-zh",
    "ernie-xbase": "nghuyong/ernie-3.0-xbase-zh",
    "text2vec-base": "./data/text2vec-base-chinese"
}

llm_model_dict = {
    "ChatGLM-6B": "THUDM/chatglm-6b",
    "ChatGLM-6B-int4": "THUDM/chatglm-6b-int4",
    "ChatGLM-6B-int8": "THUDM/chatglm-6b-int8",
    "ChatGLM-6b-int4-qe": "THUDM/chatglm-6b-int4-qe",
    "ChatGLM-6b-local": "./data/chatglm-6b"
}
都放在了对应的目录

**Comment by thomas-yanxin** [comment]
@Rivien2010 知识库文件是指你的文本文件。
![image](https://user-images.githubusercontent.com/58030051/233572712-520fd6ec-2e0f-409e-a5a5-fc3cd9c6a919.png)
![image](https://user-images.githubusercontent.com/58030051/233572819-c0a9260a-886a-4d0a-9df9-8a823ab6f24f.png)
当这里变成Download的时候再输入您的问题。

**Comment by Rivien2010** [comment]
好了 感谢！
