### ISSUE TITLE
没有GPU的电脑上不能运行

### ISSUE THREAD

**Issue by jerrycompal** [thomas-yanxin/LangChain-ChatGLM-Webui#15]
Setting CPU quantization kernel threads to 20
Using quantization cache
Applying quantization to glm layers
Traceback (most recent call last):
  File "/home/wz/.local/lib/python3.9/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/wz/.local/lib/python3.9/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/home/wz/.local/lib/python3.9/site-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/wz/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/wz/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/wz/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/wz/LangChain-ChatGLM-Webui/app.py", line 150, in predict
    resp = get_knowledge_based_answer(
  File "/home/wz/LangChain-ChatGLM-Webui/app.py", line 108, in get_knowledge_based_answer
    chatLLM.load_model(model_name_or_path=llm_model_dict[large_language_model])
  File "/home/wz/LangChain-ChatGLM-Webui/chatglm_llm.py", line 114, in load_model
    self.model = (AutoModel.from_pretrained(
  File "/home/wz/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1811, in to
    return super().to(*args, **kwargs)
  File "/home/wz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/wz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/wz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/wz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/wz/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/wz/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by thomas-yanxin** [comment]
代码确实并没有在cpu的环境中测试。但我想知道的是您cpu的环境内存是否够？

**Comment by jerrycompal** [comment]
> 代码确实并没有在cpu的环境中测试。但我想知道的是您cpu的环境内存是否够？

我的内存有256G，应该是够了，我看到app.py里有对GPU和CPU的判断，明天我再看一下。

**Comment by thomas-yanxin** [comment]
来自ChatGLM的官方Readme：“CPU 部署
如果你没有 GPU 硬件的话，也可以在 CPU 上进行推理，但是推理速度会更慢。使用方法如下（需要大概 32GB 内存）”

这里的内存应该是指运行内存，而不是硬盘。

今天我也在cpu里测试一下看看。有问题随时在这个issue同步。

感谢！

**Comment by thinkinds** [comment]
我在CPU服务器上试过了，上面那些报错不影响的，只是推理速度很慢
