### ISSUE TITLE
'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by jimfrc** [thomas-yanxin/LangChain-ChatGLM-Webui#55]
Traceback (most recent call last):
  File "C:\GLM\LangChain-ChatGLM-Webui-master\app.py", line 15, in <module>
    from chatllm import ChatLLM
  File "C:\GLM\LangChain-ChatGLM-Webui-master\chatllm.py", line 7, in <module>
    from fastchat.serve.inference import load_model as load_fastchat_model
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\fastchat\serve\inference.py", line 9, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1137, in __getattr__
    value = getattr(module, name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1136, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1148, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
'NoneType' object has no attribute 'write'

安装库后，提示这个错误，不知道哪里出了问题

**Comment by jimfrc** [comment]
换到linux也会报这个错误，但是加载本地资料库就可以了，windows还不行
