### ISSUE TITLE
提示"初始模型已成功加载，可以开始对话",也上传了一个只有几句话的txt,提问后报这个错,请问是什么原因?为什么要找D:\a\faiss-wheels\这个文件夹?

### ISSUE THREAD

**Issue by jiakuaibu** [thomas-yanxin/LangChain-ChatGLM-Webui#72]
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\Program Files\Anaconda\envs\langChainChatGLM\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Program Files\Anaconda\envs\langChainChatGLM\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\Program Files\Anaconda\envs\langChainChatGLM\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Program Files\Anaconda\envs\langChainChatGLM\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Program Files\Anaconda\envs\langChainChatGLM\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Program Files\Anaconda\envs\langChainChatGLM\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "app.py", line 215, in predict
    resp = knowladge_based_chat_llm.get_knowledge_based_answer(
  File "app.py", line 127, in get_knowledge_based_answer
    vector_store = FAISS.load_local('faiss_index', self.embeddings)
  File "D:\Program Files\Anaconda\envs\langChainChatGLM\lib\site-packages\langchain\vectorstores\faiss.py", line 449, in load_local
    index = faiss.read_index(
  File "D:\Program Files\Anaconda\envs\langChainChatGLM\lib\site-packages\faiss\swigfaiss.py", line 9795, in read_index
    return _swigfaiss.read_index(*args)
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open faiss_index\index.faiss for reading: No such file or directory

**Comment by thomas-yanxin** [comment]
没有点`知识库文件向量化`这个button
