### ISSUE TITLE
模型加载成功，但是发送会报错，帮忙看看

### ISSUE THREAD

**Issue by chenjf2015103095** [thomas-yanxin/LangChain-ChatGLM-Webui#74]
etting CPU quantization kernel threads to 24
Using quantization cache
Applying quantization to glm layers
The dtype of attention mask (torch.int64) is not bool
Running on local URL:  http://0.0.0.0:7862

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "app.py", line 215, in predict
    resp = knowladge_based_chat_llm.get_knowledge_based_answer(
  File "app.py", line 127, in get_knowledge_based_answer
    vector_store = FAISS.load_local('faiss_index', self.embeddings)
  File "/opt/conda/lib/python3.8/site-packages/langchain/vectorstores/faiss.py", line 449, in load_local
    index = faiss.read_index(
  File "/opt/conda/lib/python3.8/site-packages/faiss/swigfaiss_avx2.py", line 10206, in read_index
    return _swigfaiss_avx2.read_index(*args)
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open faiss_index/index.faiss for reading: No such file or directory

**Comment by donger0616** [comment]
请问你解决了吗，我也是一样的错误

**Comment by thomas-yanxin** [comment]
没有点`知识库文件向量化`这个button
