### ISSUE TITLE
点击知识文库向量化报错

### ISSUE THREAD

**Issue by lanhaoit** [thomas-yanxin/LangChain-ChatGLM-Webui#81]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 289, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 990, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 832, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "app.py", line 195, in init_vector_store
    file_obj.name)
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by thomas-yanxin** [comment]
https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/issues/49#issuecomment-1536201583
